name: 'AWS EC2 Wait Action'
description: 'GitHub action which waits for an EC2 instance to be running and pass status checks'
author: 'TrueMark'
inputs:
  instance-ids:
    required: true
    description: 'Instance IDs to wait for'
  timeout-ms:
    required: false
    description: 'Timeout in milliseconds'
    default: '600000'
  region:
    required: true
    description: 'AWS region to use'
runs:
  using: 'node16'
  main: 'dist/index.js'
